flask_app/main/routes.py
import os
from flask import Blueprint, render_template, request, current_app
from flask_app.models import Post

main = Blueprint("main", __name__)

############################################################################################
############################### Home page ##################################################
############################################################################################

@main.route("/")
def default_page():
    return render_template('website_loader.html')

@main.route("/home") #route is a decorator that is used to handle all the backend stuff and retun the o/p of the called function
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query\
            .order_by(Post.date_posted.desc())\
            .paginate(page=page, per_page=5) 
    return render_template("home.html", posts=posts)

############################################################################################
############################### About page #################################################
############################################################################################

@main.route("/about") #route is a decorator that is used to handle all the backend stuff and retun the o/p of the called function
def about():
    return render_template('about.html', title='About')

flask_app/templates/reset_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&family=Poppins:wght@600;700&family=Fira+Code&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <title>{{ title }}</title>
    <style>
        .container {
            padding: 20px;
            text-align: center;
            background-color: #f4f4f4;
            border-radius: 10px;
            margin: auto;
            max-width: 600px;
            font-family: 'Inter', sans-serif, monospace;
        }
        .header {
            background-color: #3c4e5c;
            color: white;
            padding: 10px 0;
            font-size: 24px;
            font-weight: bold;
        }
        .button {
            background-color: #3c4e5c;
            color: white !important;
            padding: 10px 20px;
            text-decoration: none;
            font-size: 18px;
            font-family: 'Inter', sans-serif, monospace;
            font-weight: bold;
            border-radius: 5px;
            display: inline-block;
            margin: 20px 0;
        }
        .footer {
            font-size: 14px;
            color: #777;
            margin-top: 30px;
        }
        .content-section {
            background: #ffffff;
            padding: 20px;
            border: 1px solid #e3e3e3;
            border-radius: 5px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,.05);
        }
        .content-section p .footer p{
            font-family: 'Fira Code', 'Consolas', monospace;
            background-color: #f7f7f7;
            font-size: 13px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">Password Reset Request</div>
        <div class="content-section">
            <p>Hello <strong>{{ user.username }}</strong>,</p>
            <p>We received a request to reset your password. If this was you, click the button below to reset your password:</p>
            <a href="{{ url_for('users.reset_token', token= token, _external= True)}}" class="button">Reset Password</a>
            <p>If you did not request a password reset, please ignore this email.</p>
        </div>
        <div class="footer">
            <p>Thank you,<br><strong>EnI Team</strong></p>
            <p><a href="https://shorturl.at/TWVN5" target="_blank">Visit our site</a> | <a href="mailto:swaroopgorur@gmail.com">Contact Support</a></p>
        </div>
    </div>
</body>
</html>

flask_app/templates/website_loader.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Swaroop's Website</title>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&family=Poppins:wght@600;700&family=Fira+Code&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        body, html {
            margin: 0;
            padding: 0;
            height: 100%;
            font-family: Arial, sans-serif;
            text-align: center;
            overflow-x: hidden;
        }
        .hero {
            background-image: url("{{ url_for('static', filename='images/website_load_image.jpg') }}");
            height: 100vh;
            width: 100vw;
            background-size: cover;
            background-position: center;
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            position: relative;
        }
        .hero h1 {
            font-size: 2.3rem;
            color: #3c4e5c;
            text-shadow: 3px 3px 6px rgba(0, 0, 0, 0.7);
            font-family: 'Nunito', 'Arial', sans-serif;
            margin: 0;
            position: absolute;
            left: 50%;
            top: 85px; 
            transform: translateX(-50%);
            white-space: nowrap;
            overflow: hidden;
            border-right: 4px solid #3c4e5c;
            display: inline-block;
        }
        #welcome-text {
            animation: typing-welcome 2.8s steps(10, end) 0s, blink-caret-welcome 0.75s ;   
        }
        #sitename-text {
            visibility: hidden;
            opacity: 0;
            animation: visibility-sitename 0s 3.5s forwards, typing-sitename 4s steps(20, end) 4s forwards, fade-in-sitename 0.3s 4s forwards ;
            margin-top: 80px;
        }
        .nav-button {
            padding: 15px 25px;
            color: white;
            background-color: #df6969;
            text-decoration: none;
            border-radius: 30px;
            font-size: 1.5rem;
            margin-top: 20px;
            font-family: 'Fira Code', monospace;
            animation: bounce 1.5s infinite;
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);
            transition: background-color 0.3s ease-in-out;
            position: fixed;
            right: 20px;
            bottom: 20px;
        }
        .text-body-secondary{
            color: black;
            padding: 15px 25px;
            font-size: 1.5rem;
            font-weight: bolder;
            font-family: 'Fira Code', monospace;
            position: fixed;
            right: 162px;
            bottom: 90px;
        }
        .text-body-primary{
            color: black;
            padding: 15px 25px;
            font-size: 1.5rem;
            font-weight: bolder;
            font-family: 'Fira Code', monospace;
            position: fixed;
            right: 20px;
            bottom: 60px;
        }
        .site-header {
            color: #ffffff;
            background-color: rgba(255,255,255,0.1);
            font-weight: 500;
            padding: 0.5rem 1rem;
            border-radius: 5px;
        }
        .navbar-brand {
            font-weight: bold;
            font-size: 1.5rem;
        }
        .bg-steel {
            background-color: #3c4e5c;
            box-shadow: 0 2px 4px rgba(0,0,0,.1);
        }
        .footer {
            position: fixed;
            left: 20px;
            bottom: 20px;
            color: #3c4e5c;
            font-size: 0.9rem;
            font-family: 'Nunito', 'Arial', sans-serif;
            text-align: left;
            padding: 10px;
            border-radius: 5px;
            z-index: 1000;
        }
        .footer a {
            color: #df6969;
            text-decoration: none;
            transition: color 0.3s ease-in-out;
        }
        .footer a:hover {
            color: #b54b4b;
        }
        @keyframes bounce {
            0%, 100% { transform: translateY(0); }
            50% { transform: translateY(-10px); }
        }
        @keyframes typing-welcome {
            from { width: 0; }
            to { width: 7ch; }
        }
        @keyframes typing-sitename {
            from { width: 0; }
            to { width: 10ch; }
        }
        @keyframes fade-in-sitename {
            to { opacity: 1; visibility: visible; }
        }
        @keyframes visibility-sitename {
            from { visibility: hidden; }
            to { visibility: visible; }
        }
        @keyframes blink-caret-welcome {
            from, to { border-color: transparent; }
            50% { border-color: #3c4e5c; }
        }
    </style>
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{{url_for('main.default_page')}}">
                    <i class="fas fa-microphone-alt"></i> Echoes n Insights
                </a>
            </div>
        </nav>
    </header>
    <main role="main">
        <div class="hero">
            <div>
                <h1 id="welcome-text"><i>Echoing</i></h1>
                <h1 id="sitename-text"><i>Your Insights</i></h1>
                <p class="text-body-secondary">Enter</p>
                <p class="text-body-primary">Echoing Space ▼</p>
                <a href="{{url_for('main.home')}}" class="nav-button">Explore Blogs</a>
            </div>
        </div>
    </main>
    <footer class="footer">
        <div class="container">
            <p>Developed with <i class="fas fa-heart" style="color: red;"></i><br>
                By <a href="https://2wablv8f9lz.typeform.com/to/gqCLiwuZ" target="_blank">Swaroop GS</a>
            </p>
            <p>
                <a href="https://wa.me/9481072265" target="_blank" title="WhatsApp">
                    <i class="fab fa-whatsapp" style="font-size: 24px; color: #25D366;"></i>
                </a>
                <a href="https://www.instagram.com/swaroop.gorur" target="_blank" title="Instagram">
                    <i class="fab fa-instagram" style="font-size: 24px; color: #C13584;"></i>
                </a>
                <a href="https://www.linkedin.com/in/swaroop-gorur-977708a0" target="_blank" title="LinkedIn">
                    <i class="fab fa-linkedin" style="font-size: 24px; color: #0077B5;"></i>
                </a>
            </p>
        </div>
    </footer>
    
</body>
</html>