Flask_App_Linux/flask_app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length


######################################################################################
################################# Post Form ##########################################
######################################################################################

class PostForm(FlaskForm):
    title = StringField("Title",validators=[DataRequired()])
    content = TextAreaField("Content", validators=[DataRequired(), Length(min=30, max=10000)])
    submit = SubmitField("Post")

Flask_App_Linux/flask_app/main/routes.py
import os
from flask import Blueprint, render_template, request, current_app
from flask_app.models import Post

main = Blueprint("main", __name__)

############################################################################################
############################### Home page ##################################################
############################################################################################

@main.route("/")
def default_page():
    return render_template('website_loader.html')

@main.route("/home") #route is a decorator that is used to handle all the backend stuff and retun the o/p of the called function
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query\
            .order_by(Post.date_posted.desc())\
            .paginate(page=page, per_page=5) 
    return render_template("home.html", posts=posts)

############################################################################################
############################### About page #################################################
############################################################################################

@main.route("/about") #route is a decorator that is used to handle all the backend stuff and retun the o/p of the called function
def about():
    return render_template('about.html', title='About')

Flask_App_Linux/flask_app/posts/routes.py
from flask import Blueprint, render_template, abort, flash, request, redirect, url_for
from flask_login import current_user, login_required
from flask_app import db
from flask_app.models import Post
from flask_app.posts.forms import PostForm
from flask_app.posts.utils import analyze_content, is_content_appropriate


posts = Blueprint("posts", __name__)

############################################################################################
########################## Create, Fetch, Update and Delete Posts ##########################
############################################################################################

#this route is used to create new posts
@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        
        print(f"Analyzing content: '{title} {content}'")
        analysis_result = analyze_content(title + " " + content)
        
        if analysis_result is None:
            flash("Unable to analyze post content. Please try again later.", "warning")
        elif is_content_appropriate(analysis_result):
            author = current_user
            post = Post(title=title, content=content, author=author)
            db.session.add(post)
            db.session.commit()
            flash("Your post has been created successfully!", "success")
            return redirect(url_for('main.home'))
        else:
            flash("Your post contains inappropriate content and cannot be published.", "danger")
    return render_template("create_post.html", title="New Post", form=form, legend="New Post")


#this route is used to fetch the posts if exists else throw an error
@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("posts.html", title=post.title, post=post)


#this route is used to update the posts
@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        analysis_result = analyze_content(form.title.data + " " + form.content.data)
        if is_content_appropriate(analysis_result):
            post.title = form.title.data
            post.content = form.content.data
            db.session.commit()
            flash("Your Post has been updated successfully!", "success")
            return redirect(url_for('posts.post', post_id=post_id))
        else:
            flash("Your post contains inappropriate content and cannot be published.", "danger")
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content 
    return render_template("create_post.html", title="Update Post", form=form, legend="Update Post")

#this route is used to delete the post
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your Post has been deleted successfully!!", "success")
    return redirect(url_for('main.home'))

Flask_App_Linux/flask_app/users/routes.py
import os
from flask import Blueprint, render_template, flash, request, redirect, url_for
from flask_login import login_user, current_user, logout_user, login_required
from flask_app import db, bcrypt
from flask_app.models import Post, User
from flask_app.users.forms import RegisterationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flask_app.users.utils import save_picture, send_reset_email


#creating an instance of Blueprint module
users = Blueprint("users", __name__)

############################################################################################
############################### Registeration page #########################################
############################################################################################

@users.route("/register", methods= ['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = RegisterationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username = form.username.data, email = form.email.data, password = hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account has been created! Please procced to login!', 'success')
        return redirect(url_for('users.login'))
    return render_template("register.html", title= "Register", form=form)

############################################################################################
############################### Login page #################################################
############################################################################################

@users.route("/login", methods = ['GET', 'POST'])
def login():
    #if the current user is authenticated then we are redirecting it to the home page
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email= form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next') #args is a dictionary
            #redirect to the next page if the next parameter is present else redirect to the home page.
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f"Login unsuccessful. Please check email and password", "danger")
    return render_template("login.html", title= "Login", form=form)

############################################################################################
############################### Logout Button ##############################################
############################################################################################

@users.route("/logout")
def logout():
    logout_user() #using the function from the flask_login module to logout all the users and clears the remember cookies as well.
    return redirect(url_for('main.home'))

############################################################################################
############################### Account Details ############################################
############################################################################################


#################### Routes for Account info ######################################

@users.route("/account", methods = ['GET', 'POST'])
@login_required #this decorator is used to notify that for accounts route to be accessed we need to login first.
#If you decorate a view with this, it will ensure that the current user is logged in and authenticated before calling the actual view. 
# (If they are not, it calls the LoginManager.unauthorized callback.)
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            #Removing the previously used picture from storage before saving new
            prev_picture = os.path.join(users.root_path, 'static/profile_pics', current_user.image_file)
            if os.path.exists(prev_picture) and os.path.basename(prev_picture) != 'default.jpg':
                os.remove(prev_picture)

            #use save_picture function to get the picture name and save the resized image in the picture path.
            picture_name = save_picture(form.picture.data)
            current_user.image_file = picture_name
            
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Account details have been updated successfully", "success")
        return redirect(url_for('users.account'))
    elif request.method == 'GET': #this by defalt populates the current user details in the form.
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template("account.html", title= "Account", image_file= image_file, form= form)




############################################################################################
##################################### Post Owner ###########################################
############################################################################################

@users.route("/user/<string:username>") 
def user_post(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username= username).first_or_404()
    posts = Post.query\
        .filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5) 
    return render_template("user_posts.html", posts=posts, user=user)


############################################################################################
##################################### Reset Password #######################################
############################################################################################


#--------------------------------------------------------------------------------------------------
#reset request is a route to place a reset request using the email id when we click forgot password

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    #user should be logged out to raise a reset request
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        send_reset_email(user= user)
        flash("An email has been sent to reset the password! Please check your Inbox !!", "info")
        return redirect(url_for('users.login'))
    
    return render_template("reset_request.html", form= form, title= "Reset Password")

#--------------------------------------------------------------------------------------------------
#reset password is a route to change the password by clicking the link recieved in the email id.
@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    #user should be logged out to reset the password
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    user = User.verify_reset_token(token=token)
    if user is None:
        flash("This is an invalid/ expired token", "warning")
        return redirect(url_for('users.reset_request'))
    
    form =  ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated! Please procced to login!', 'success')
        return redirect(url_for('users.login'))
    
    return render_template("reset_token.html", form= form, title= "Reset Password")

Flask_App_Linux/flask_app/templates/about.html
{% extends "base.html" %}
{% block content %}
    <h1 class="about-heading">About Us</h1>

    <p class="about-paragraph">
    Welcome to <span>Echoes n Insights</span>, where creativity meets expression. We are passionate about writing and sharing ideas that inspire, inform, and entertain. 
    Our platform is dedicated to cultivating a community of writers and readers who value insightful content and meaningful conversations.
    </p><br/>

    <p class="about-paragraph">
    At <span>Echoes n Insights</span>, we believe that every voice deserves to be heard. Whether you're a seasoned writer or just starting your blogging journey, 
    this is your space to explore, create, and connect. Join us as we embark on a journey of discovery through the power of words.
    </p><br>

    <button class="join-button" onclick="window.location.href='register';">Join Our Community</button>
{% endblock content %}

Flask_App_Linux/flask_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% if title %}
        <title>Swaroop's Website-{{ title }}</title>
    {% else %}
        <title>Swaroop's Website</title>
    {% endif %}
    
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&family=Poppins:wght@600;700&family=Fira+Code&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" crossorigin="anonymous">
</head>
<body>   
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand" href="/">
                    <i class="fas fa-microphone-alt"></i> Echoes n Insights
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.home') }}"><i class="fas fa-home"></i> Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.about') }}"><i class="fas fa-info-circle"></i> About</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('posts.new_post') }}"><i class="fas fa-plus-circle"></i> New Post</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.account') }}"><i class="fas fa-user-circle"></i> Account</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.login') }}"><i class="fas fa-sign-in-alt"></i> Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.register') }}"><i class="fas fa-user-plus"></i> Register</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container mt-4">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Latest Updates</h3>
                    <p class='text-muted'>Check out recent blog posts and announcements.
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light"><i class="fas fa-newspaper"></i> Latest Posts</li>
                            <li class="list-group-item list-group-item-light"><i class="fas fa-bullhorn"></i> Announcements</li>
                            <li class="list-group-item list-group-item-light"><i class="fas fa-calendar-alt"></i> Calendars</li>
                            <li class="list-group-item list-group-item-light"><i class="fas fa-images"></i> Images</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>
    <footer class="footer">
        <div class="container">
            <p>Developed with <i class="fas fa-heart" style="color: red;"></i> by <a href="https://2wablv8f9lz.typeform.com/to/gqCLiwuZ" target="_blank">Swaroop GS</a></p>
            <p>
                <a href="https://wa.me/9481072265" target="_blank" title="WhatsApp"><i class="fab fa-whatsapp" style="font-size: 24px; color: #25D366;"></i></a>
                <a href="https://www.instagram.com/swaroop.gorur" target="_blank" title="Instagram"><i class="fab fa-instagram" style="font-size: 24px; color: #C13584;"></i></a>
                <a href="https://www.linkedin.com/in/swaroop-gorur-977708a0" target="_blank" title="LinkedIn"><i class="fab fa-linkedin" style="font-size: 24px; color: #0077B5;"></i></a>
            </p>
        </div>
    </footer>    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

Flask_App_Linux/flask_app/templates/home.html
{% extends "base.html" %}
{% block content %}
    {% for post in posts.items %}
    <article class="media content-section">
        <!------------------------------------------------- Image Display-------------------------------------------------------------->
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/'+post.author.image_file) }}">
        <!------------------------------------------------- Main div ------------------------------------------------------------------>
        <div class="media-body d-flex flex-column">
          <!------------------------------------------------- Username and Date div -------------------------------------->
          <div class="d-flex justify-content-between align-items-center">
            <a class="mr-2" href="{{ url_for('users.user_post', username= post.author.username) }}" style="margin-bottom: 2px; border-bottom: 1px solid #8d8b8b;">{{ post.author.username }}</a>
            <small class="text-muted" style="margin-bottom: 2px; ">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          </div><br/>
          <!------------------------------------------------- Post title  ------------------------------------------------>
          <div class="d-flex justify-content-between align-items-center">
            <h2 class="mb-0">
                <a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
            </h2>
          </div><br/>
          <!------------------------------------------------- Post content ------------------------------------------------>
          <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    {% endfor %}
    <!--------------------------------------------- Pagination ---------------------------------------------------------->
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-dark mb-4" href="{{ url_for('main.home', page= page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-dark mb-4" href="{{ url_for('main.home', page= page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

Flask_App_Linux/flask_app/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="" enctype="multipart/form-data"> <!-- action="" -> routes to the same route we are in when posted-->
            {{ form.hidden_tag() }} <!-- Adding csrf token-->
            <fieldset class="form-group">
                <legend class="styled-legend"><h3>LOG IN</h3></legend><br><br>

                <div class="form-group">
                    <h6> <i class="fas fa-envelope"></i>&ensp;{{ form.email.label(class="form-control-label") }}</h6>                    
                    <!-- Handling the errors -->
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                            <span> {{ error }}</span>
                            {% endfor %}
                        </div>
                    {%else%}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                    
                </div><br>
                <div class="form-group">
                    <h6><i class="fas fa-key"></i>&ensp;{{ form.password.label(class="form-control-label") }}</h6>
                    <!-- Handling the errors -->
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                            <span> {{ error }}</span>
                            {% endfor %}
                        </div>
                    {%else%}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <br/>
                <div class="form-check">
                    <strong>{{ form.remember.label(class="form-check-label")}}</strong>
                    {{ form.remember(class="form-check-input")}}
                </div>

            </fieldset>
            <div class="form-group">
                <br/>
                {{ form.submit(class="btn btn-dark")}}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}" style="color: #2104a1; font-weight: bold">Forgot Password <i class="fa-solid fa-question"></i></a>
                </small>
            </div>

        </form>
    </div>
    <div class="border-top pt-3">
        <p class="text-body-secondary ml-2">
            <strong>Need An Account?</strong> <a href="{{ url_for('users.register') }}" style="color: #2104a1; font-weight: bold">Sign Up</a>
        </p>
    </div>
{% endblock content %}

Flask_App_Linux/flask_app/templates/posts.html
{% extends "base.html" %}
{% block content %}
<article class="content-section">
  <div class="d-flex">
    <!-- Image Display -->
    <img class="rounded-circle article-img me-3" src="{{ url_for('static', filename='profile_pics/'+post.author.image_file) }}" alt="{{ post.author.username }}'s profile picture">
    
    <!-- Main content -->
    <div class="flex-grow-1 ms-3">
      <!-- Username and Date -->
      <div class="d-flex justify-content-between align-items-center mb-2">
        <a class="me-2" href="{{ url_for('users.user_post', username=post.author.username) }}" style="border-bottom: 1px solid #8d8b8b;">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
      </div>
      
      <!-- Post title and buttons -->
      <div class="d-flex justify-content-between align-items-start mb-2">
        <h2 class="mb-0">
          <a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
        </h2>
        {% if post.author == current_user %}
        <div>
          <a class="btn btn-secondary btn-sm me-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
          <button class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
        </div>
        {% endif %}
      </div>     
      <!-- Post content -->
      <div class="article-container">
        <input type="checkbox" id="toggle-content">
          <p class="article-content">{{ post.content }}</p>
        <label for="toggle-content" class="read-more-label"></label>
      </div>
  </div>
</article>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete the Post?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure? Do you still wish to delete your contribution?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <form method="POST" action="{{ url_for('posts.delete_post', post_id=post.id) }}">
          <input type="submit" class="btn btn-danger" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

Flask_App_Linux/flask_app/templates/reset_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&family=Poppins:wght@600;700&family=Fira+Code&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <title>{{ title }}</title>
    <style>
        .container {
            padding: 20px;
            text-align: center;
            background-color: #f4f4f4;
            border-radius: 10px;
            margin: auto;
            max-width: 600px;
            font-family: 'Inter', sans-serif, monospace;
        }
        .header {
            background-color: #3c4e5c;
            color: white;
            padding: 10px 0;
            font-size: 24px;
            font-weight: bold;
        }
        .button {
            background-color: #3c4e5c;
            color: white !important;
            padding: 10px 20px;
            text-decoration: none;
            font-size: 18px;
            font-family: 'Inter', sans-serif, monospace;
            font-weight: bold;
            border-radius: 5px;
            display: inline-block;
            margin: 20px 0;
        }
        .footer {
            font-size: 14px;
            color: #777;
            margin-top: 30px;
        }
        .content-section {
            background: #ffffff;
            padding: 20px;
            border: 1px solid #e3e3e3;
            border-radius: 5px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,.05);
        }
        .content-section p .footer p{
            font-family: 'Fira Code', 'Consolas', monospace;
            background-color: #f7f7f7;
            font-size: 13px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">Password Reset Request</div>
        <div class="content-section">
            <p>Hello <strong>{{ user.username }}</strong>,</p>
            <p>We received a request to reset your password. If this was you, click the button below to reset your password:</p>
            <a href="{{ url_for('users.reset_token', token= token, _external= True)}}" class="button">Reset Password</a>
            <p>If you did not request a password reset, please ignore this email.</p>
        </div>
        <div class="footer">
            <p>Thank you,<br><strong>EnI Team</strong></p>
            <p><a href="https://shorturl.at/TWVN5" target="_blank">Visit our site</a> | <a href="mailto:swaroopgorur@gmail.com">Contact Support</a></p>
        </div>
    </div>
</body>
</html>